# Generated by Django 2.0.13 on 2019-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='工具名称')),
                ('url_path', models.CharField(max_length=150, verbose_name='工具来源')),
            ],
            options={
                'verbose_name': '常用工具',
                'verbose_name_plural': '常用工具',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('wz', '网站'), ('rj', '软件'), ('qt', '其他')], max_length=4, verbose_name='分类')),
                ('add_time', models.DateTimeField(verbose_name='存储时间')),
                ('url_path', models.CharField(max_length=150, verbose_name='存储地点')),
                ('explain', models.TextField(verbose_name='简介')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
    ]
