# Generated by Django 2.0.13 on 2019-03-02 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='url_path',
            field=models.CharField(default=datetime.datetime(2019, 3, 2, 22, 48, 21, 198944), max_length=150, verbose_name='存储地点'),
        ),
    ]
