# Generated by Django 2.0.13 on 2019-03-02 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190302_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 22, 50, 44, 401285), verbose_name='存储时间'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='url_path',
            field=models.CharField(max_length=150, verbose_name='存储地点'),
        ),
    ]
