# Generated by Django 2.0.13 on 2019-02-25 10:20

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 18, 20, 24, 702416), verbose_name='添加时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点赞量')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
    ]
