# Generated by Django 2.0.13 on 2019-02-26 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 8, 57, 55, 193409), verbose_name='添加时间'),
        ),
    ]
