# Generated by Django 2.0.13 on 2019-02-26 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190226_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 9, 50, 40, 766108), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='blog_lables',
            field=models.ManyToManyField(to='blogs.Blogs', verbose_name='博客'),
        ),
    ]
