# Generated by Django 2.0.13 on 2019-02-26 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190226_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 9, 58, 7, 918802), verbose_name='添加时间'),
        ),
    ]
