# Generated by Django 2.0.13 on 2019-02-26 06:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190226_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondel', models.CharField(default='', max_length=20, verbose_name='博客类别')),
            ],
            options={
                'verbose_name': '博客类别',
                'verbose_name_plural': '博客类别',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='lable',
            field=models.ManyToManyField(to='blogs.Labels'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 14, 56, 5, 407225), verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_mondel',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.Categorys', verbose_name='博客类别'),
        ),
    ]
