# Generated by Django 2.0.13 on 2019-02-26 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190226_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 14, 56, 12, 372960), verbose_name='添加时间'),
        ),
    ]
