# Generated by Django 2.0.13 on 2019-02-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190226_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 14, 57, 30, 954403), verbose_name='添加时间'),
        ),
    ]
