# Generated by Django 2.0.13 on 2019-02-26 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20190226_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 15, 2, 11, 6323), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 15, 2, 11, 4324), verbose_name='添加时间'),
        ),
    ]
