# Generated by Django 2.0.13 on 2019-03-02 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20190226_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(default='无名', max_length=15, verbose_name='笔名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('conten', models.CharField(max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name': '联系',
                'verbose_name_plural': '联系',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 14, 7, 12, 901422), verbose_name='添加时间'),
        ),
    ]
