# Generated by Django 2.0.13 on 2019-03-02 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20190302_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 15, 36, 36, 657713), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='conten',
            field=models.TextField(max_length=500, verbose_name='内容'),
        ),
    ]
