# Generated by Django 2.0.13 on 2019-03-02 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20190302_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 22, 42, 11, 965081), verbose_name='添加时间'),
        ),
    ]
