# Generated by Django 2.0.13 on 2019-03-02 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20190302_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 22, 48, 21, 192947), verbose_name='添加时间'),
        ),
    ]
